ACCOUNT = ''
PWD = ''

MONGO_HOST = ''
MONGO_PORT = 30000
MONGO_DATABASE = ''
MONGO_USERNAME = ''
MONGO_PASSWORD= ''
MONGO_COLLECTION = ''

IMPLICIT_WAIT_DRIVER = 15

SAVE_COMPAINT_BATCH = 10
RESTART_EXCEPTION_COUNT = 20
RETRY_COMPLAINT_DETAIL_TIMEOUT_COUNT = 2
SLEEP_NEXT_COMPLAINTS_PAGE = 1
SLEEP_NEXT_COMPLAINT = 1

SLEEP_NEXT_REPORTER = 0.5
SLEEP_NEXT_REPORTS_PAGE = 0.5
